Marvel/Models/Character.cs
using Marvel.Api.Model.Lists;
using System.ComponentModel.DataAnnotations.Schema;

namespace Marvel.Models;

public class Character
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Modified { get; set; }
    public string ResourceURI { get; set; }
    public string Image { get; set; }

    [NotMapped]
    public List<MarvelUrl> Urls { get; set; }

    [NotMapped]
    public MarvelImage Thumbnail { get; set; }

    [NotMapped]
    public ComicList Comics { get; set; }

    [NotMapped]
    public StoryList Stories { get; set; }

    [NotMapped]
    public EventList Events { get; set; }

    [NotMapped]
    public SeriesList Series { get; set; }

    public bool Favorite { get; set; } = false;

    public string GetImage()
    {
       Image = $"{Thumbnail.Path}.{Thumbnail.Extension}";
        return Image;
    }
}

Marvel/Models/CharacterDataContainer.cs
namespace Marvel.Models;

public class CharacterDataContainer
{
    public int Offset { get; set; }

    public int Limit { get; set; }

    public int Total { get; set; }

    public int Count { get; set; }

    public List<Character> Results { get; set; }
}

Marvel/Models/CharacterDataWrapper.cs
namespace Marvel.Models;

public class CharacterDataWrapper
{
    public int Code { get; set; }

    public string Status { get; set; }

    public string Copyright { get; set; }

    public string AttributionText { get; set; }

    public string AttributionHTML { get; set; }

    public CharacterDataContainer Data { get; set; }

    public string Etag { get; set; }
}

Marvel/Models/ErrorViewModel.cs
namespace Marvel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Marvel/Models/MarvelImage.cs
namespace Marvel.Models;

public class MarvelImage
{
    public string Path { get; set; }
    public string Extension { get; set; }
}

Marvel/Models/MarvelUrl.cs
namespace Marvel.Models;

public class MarvelUrl
{
    public string Type { get; set; }
    public string Url { get; set; }
}

Marvel/Controllers/CharactersController.cs
#nullable disable

using Marvel.Data;
using Marvel.Models;
using Marvel.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tools.Models;

namespace Marvel.Controllers;

[Route("/[controller]")]
[Controller]
public class CharactersController : Controller
{
    private readonly DataContext _context;
    private readonly IService _service;

    public CharactersController(DataContext context, IService service)
    {
        _context = context;
        _service = service;
    }

    // GET: Characters
    [HttpGet]
    public async Task<IActionResult> Index(string sortExpression = "", int page = 1, int pageSize = 5)
    {
        SortModel sort = new SortModel();
        sort.AddColumn("id");
        sort.AddColumn("name");
        sort.AddColumn("favorite");
        sort.ApplySort(sortExpression);
        ViewData["sort"] = sort;

        PaginatedList<Character> characters = await _service.GetCharacters(sort.SortProperty, sort.OrderBy, page, pageSize);

        var pager = new PagerModel(characters.TotalRecords, page, pageSize);
        pager.SortExpression = sortExpression;
        this.ViewBag.Pager = pager;

        return View(characters);
    }

    [HttpGet("/[controller]/{name}")]
    public async Task<IActionResult> GetCharacter(string GetCharacter)
    {
        if (GetCharacter == null)
        {
            return NotFound();
        }

        if (_service.CharacterExists(GetCharacter))
        {
            var character = _context.characterContext.FirstOrDefault(c => c.Name == GetCharacter);

            List<Character> result = new List<Character>() { character };

            return View(result);
        }
        else
        {
            var result = await _service.GetCharacters(GetCharacter);

            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
    }

    // GET: Characters/Details/5
    [Route("/[controller]/details")]
    [HttpGet]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var character = await _context.characterContext
            .FirstOrDefaultAsync(m => m.Id == id);
        if (character == null)
        {
            return NotFound();
        }

        return View(character);
    }

    // GET: Characters/Edit/5
    [Route("/[controller]/edit/{id}")]
    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var character = await _context.characterContext.FindAsync(id);
        if (character == null)
        {
            return NotFound();
        }
        return View(character);
    }

    // POST: Characters/Edit/5
    [Route("/[controller]/edit/{id}")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Modified,ResourceURI,Image,Favorite")] Character character)
    {
        if (id != character.Id)
        {
            return NotFound();
        }

        if (character.Description == null)
            character.Description = String.Empty;

        if (character.Favorite == true && !_service.ValidateFavorite())
        {
            character.Favorite = true;
        }
        else
        {
            character.Favorite = false;
        }

        try
        {
            _context.Update(character);
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!_service.CharacterExists(character.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
        return RedirectToAction(nameof(Index));
    }
}

Marvel/Controllers/HomeController.cs
using Marvel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Marvel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Marvel/Views/Characters/Details.cshtml
@model Marvel.Models.Character

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .container{
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    align-items: center;
}
    .img-responsive{
    width: 100%;
    height: 250px;
        margin-bottom: 10px;
        border:1px solid black; 
    }
    .image{
        margin-bottom: 10px;
    }
    .content{
        display: flex;
    }

</style>

<h1>Details</h1>

<div class="container">
    <h4>Character</h4>
    <hr />
    <div class="image">
        <img class="img-responsive rounded box" src="@Model.Image" alt="">
    </div>
    <div class="content">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Modified)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Modified)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ResourceURI)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ResourceURI)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Favorite)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Favorite)
            </dd>
        </dl>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Marvel/Views/Characters/Edit.cshtml
@model Marvel.Models.Character

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Character</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResourceURI" class="control-label"></label>
                <input asp-for="ResourceURI" class="form-control" />
                <span asp-validation-for="ResourceURI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Favorite" /> @Html.DisplayNameFor(model => model.Favorite)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Marvel/Views/Characters/GetCharacter.cshtml
@model IEnumerable<Marvel.Models.Character>

@{
    ViewData["Title"] = "Heroes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Heroes</h1>

<div class="search-single">
    @using (Html.BeginForm("GetCharacter", "Characters", FormMethod.Get))
    {
        <input type="text" name="GetCharacter" placeholder="Search" />
        <input type="submit" value="Submit" />
    }
    <div class="p">
        <p>Only 5 Characters can be Favorite</p>
        <p>If you Favorite with more than 5 he will disregard and not mark as Favorite</p>
    </div>
</div>
<table class="table table-sortable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Favorite)
            </th>
            <th>
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Favorite)
                </td>
                <td>
                    <a asp-controller="Characters" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Characters" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Marvel/Views/Characters/Index.cshtml
@using Tools.Models;
@model IEnumerable<Marvel.Models.Character>

@{
    ViewData["Title"] = "Heroes";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SortModel sort = (SortModel)ViewData["sort"];

    PagerModel pager = ViewBag.Pager;
}

<style>
    #botBar {
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        align-items: baseline;
        justify-content: center;
    }
</style>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <h1>Heroes</h1>
                <div class="search-single">
                    @using (Html.BeginForm("GetCharacter", "Characters", FormMethod.Get))
                    {
                        <input type="text" name="GetCharacter" placeholder="Search" />
                        <input type="submit" value="Submit" />
                    }
                    <div class="p">
                        <p>Only 5 Characters can be Favorite</p>
                        <p>If you Favorite with more than 5 he will disregard and not mark as Favorite</p>
                    </div>
                </div>
                <table class="table" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                <a asp-action="Index" asp-route-sortExpression="@sort.GetColumn("id").SortExpression">
                                    @Html.DisplayNameFor(model => model.Id)
                                </a>
                                <i class="@sort.GetColumn("id").SortIcon" arial-hidden="true"></i>
                            </th>
                            <th>
                                <a asp-action="Index" asp-route-sortExpression="@sort.GetColumn("name").SortExpression">
                                    @Html.DisplayNameFor(model => model.Name)
                                </a>
                                <i class="@sort.GetColumn("name").SortIcon" arial-hidden="true"></i>
                            </th>
                            <th>
                                <a asp-action="Index" asp-route-sortExpression="@sort.GetColumn("favorite").SortExpression">
                                    @Html.DisplayNameFor(model => model.Favorite)
                                </a>
                                <i class="@sort.GetColumn("favorite").SortIcon" arial-hidden="true"></i>
                            </th>
                            <th>
                                Options
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Favorite)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-12" id="botBar">
                <partial name="_showItems" model="@pager" />
                <partial name="_pagerBar" model="@pager" />
            </div>
        </div>
    </div>
</body>
</html>

Marvel/Views/Characters/SingleCharacter.cshtml
@model IEnumerable<Marvel.Models.Character>

@{
    ViewData["Title"] = "Heroes";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<h1>Heroes</h1>

<div class="search-single">
    @using (Html.BeginForm("SingleCharacter", "Characters", FormMethod.Get))
    {
        <input type="text" name="nameCharacter" placeholder="Search" />
        <input type="submit" value="Submit" />
    }
    <div class="p">
        <p>Only 5 Characters can be Favorite</p>
        <p>If you Favorite with more than 5 he will disregard and not mark as Favorite</p>
    </div>
</div>
<table class="table table-sortable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Favorite)
            </th>
            <th>
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Favorite)
                </td>
                <td>
                    <a asp-controller="Characters" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Characters" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Characters" asp-action="SingleCharacter" asp-route-pg="@pge">@pge</a>
                </li>
            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Characters" asp-action="SingleCharacter" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Characters" asp-action="SingleCharacter" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

<script src="~/js/site.js"></script>

Marvel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Click on Characters to retrieve the list</p>
</div>

Marvel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marvel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Marvel.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marvel_GC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Characters" asp-action="Index">Characters</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

Marvel/Views/Shared/_pagerBar.cshtml
@model Tools.Models.PagerModel

<style>
    .page-item.active {
        z-index: 3;
        color: #fff;
        background-color: rgba(0, 0, 200, 0.1);
        border-color: rgba(0, 0, 200, 0.1);
    }
    #botBar{
        display: flex;
    }
</style>

<div class="container mt-1" id="botBar">
    <ul class="pagination justify-content-end">

        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-action="@Model.Action" asp-route-page="1" asp-route-pageSize="@Model.PageSize" asp-route-sortExpression="@Model.SortExpression">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="@Model.Action" asp-route-page="@(Model.CurrentPage - 1)" asp-route-pageSize="@Model.PageSize" asp-route-sortExpression="@Model.SortExpression">Previous</a>
            </li>
        }
        @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
        {
            <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                @if (pge != Model.CurrentPage)
                {
                    <a class="page-link" asp-action="@Model.Action" asp-route-page="@pge" asp-route-pageSize="@Model.PageSize" asp-route-sortExpression="@Model.SortExpression">@pge</a>
                }
                else
                {
                    <span class="page-link">@pge</span>
                }
            </li>
        }
        
        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" asp-action="@Model.Action" asp-route-page="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize" asp-route-sortExpression="@Model.SortExpression">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="@Model.Action" asp-route-page="@(Model.TotalPages)" asp-route-pageSize="@Model.PageSize" asp-route-sortExpression="@Model.SortExpression">Last</a>
            </li>
        }
    </ul>
</div>

Marvel/Views/Shared/_showItems.cshtml
@model Tools.Models.PagerModel

<style>
    .btn-group {
        position: relative;
        display: inline-flex;
        vertical-align: middle;
        justify-content: flex-end;
        align-items: center;
        align-content: center;
        flex-wrap: nowrap;
        flex-direction: row;
    }
</style>

<div class="col-3 btn-group p-1">
    <span class="col-5">
        Rows per Page:
    </span>
    <span class="col-5">
        <select class="form-control" id="pageSelector" asp-items="@Model.GetPageSize();" onchange="ChangePageSize(this);"></select>
    </span>
</div>

<div class="col-4 btn-group justify-content-center">
    <p>
        Showing @Model.CurrentPage / @Model.TotalPages Pages
    </p>
</div>

<script>
    function ChangePageSize(obj) {
        var controller = '@this.ViewContext.RouteData.Values["controller"].ToString()';

        window.location.href = "?" + controller + "/@Model.Action" + "&pageSize=" + obj.value + "&sortExpression=" + "@Model.SortExpression";
    }

</script>